name: Test BFHL API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Start API server
      run: |
        npm start &
        sleep 10
    
    - name: Run tests
      run: |
        npm install -g axios
        node test.js
    
    - name: Test API endpoints
      run: |
        curl -f http://localhost:3000/ || exit 1
        curl -f -X POST http://localhost:3000/bfhl \
          -H "Content-Type: application/json" \
          -d '{"data": ["a", "1", "334", "4", "R", "$"]}' || exit 1
